name: memory-mall

volumes:
  postgres_vol: { }

services:
  nginx:
    container_name: memory-mall-nginx
    image: nginx:1.26
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www
    restart: no
    depends_on:
      - express
      - nuxt

  express:
    container_name: memory-mall-express
    build:
      context: .
      dockerfile: express.dockerfile
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    restart: no
    depends_on:
      - postgres

  nuxt:
    container_name: memory-mall-nuxt
    build:
      context: .
      dockerfile: nuxt.dockerfile
    ports:
      - "3001:3000"
    command: npm run dev
    volumes:
      - ./frontend:/app
    env_file:
      - ./.env
    restart: no
    depends_on:
      - express

  postgres:
    container_name: memory-mall-postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: MemoryMallDB
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: database123
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    restart: no

  pg-admin:
    container_name: memory-mall-pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - ./backend/src/db/servers.json:/pgadmin4/servers.json
    restart: no
    depends_on:
      - postgres