events {

}
http {
    include /etc/nginx/mime.types;
    server {
        listen 80 default_server;
        root /var/www/public;

        index index.html;

        # Try serving public static files; if none found, internally rewrite URI to 'index.php + URL args'
        location / {
            try_files $uri $uri/ /index.html?$args;
        }
    }
}
